/**
 * VITALIS — Scripts de Meditação e Afirmações
 * Chakra: Muladhara (Raiz) — 256Hz
 * Tema: Terra, Enraizamento, Corpo, Nutrição Consciente
 *
 * Formato: array de strings — cada item = uma "unidade de respiração"
 * Compatível com ElevenLabs TTS + drone vitalis-drone.mp3 como fundo
 */

export const MEDITACOES_VITALIS = [
  {
    id: 'gratidao_corpo',
    nome: 'Gratidão ao Corpo',
    descricao: 'Meditação para reconectar com o teu corpo e agradecer tudo o que ele faz por ti todos os dias.',
    duracao_min: 8,
    categoria: 'meditacao',
    icone: '🌱',
    drone: 'vitalis-drone.mp3',
    script: [
      'Fecha os olhos. Senta-te confortavelmente.',
      'Coloca as mãos sobre as coxas, com as palmas para cima.',
      'Respira fundo. Sente o ar a entrar no teu corpo.',
      'Esse mesmo corpo que respira agora... faz isso há anos, sem que tu peças.',
      'O teu coração bateu hoje. Sem esforço teu. Só porque sim.',
      'Os teus pulmões encheram-se de ar. Automaticamente.',
      'Pensa em tudo o que o teu corpo faz, sem precisar que lhe digas.',
      'Digere. Cicatriza. Regula. Movimenta.',
      'Quantas vezes já criticaste esse mesmo corpo?',
      'Quantas vezes olhaste para ele com insatisfação?',
      'Hoje, vamos fazer diferente.',
      'Coloca uma mão sobre o coração. Sente o calor da tua própria mão.',
      'Diz ao teu corpo, em silêncio: obrigado.',
      'Obrigado por continuares. Por não desistires. Por carregares a minha vida.',
      'Inspira essa gratidão... deixa-a assentar.',
      'O teu corpo não é o teu inimigo. É a tua casa.',
      'Quando abrires os olhos, olha para ele com um pouco mais de ternura.',
      'Ele merece isso. Tu mereces isso.',
    ],
  },
  {
    id: 'relacao_comida',
    nome: 'A Minha Relação com a Comida',
    descricao: 'Meditação para explorar e curar a tua relação emocional com a alimentação, sem julgamento.',
    duracao_min: 10,
    categoria: 'meditacao',
    icone: '🍽️',
    drone: 'vitalis-drone.mp3',
    script: [
      'Fecha os olhos. Respira fundo três vezes.',
      'Pensa na tua relação com a comida. Não o que comes. Como te sentes quando comes.',
      'Há culpa depois de certas refeições?',
      'Há recompensa em certos alimentos?',
      'Há momentos em que comes sem sequer ter fome?',
      'Não há respostas certas ou erradas aqui. Só honestidade.',
      'A comida é muito mais do que nutrição.',
      'É conforto. É celebração. É memória. É controlo. É amor.',
      'Nenhum de nós aprendeu a comer apenas por fome. Aprendemos muito mais do que isso.',
      'Imagina a tua criança mais nova. A que aprendeu que doce era recompensa.',
      'Ou que comer tudo no prato era obrigação.',
      'Essas crenças ainda vivem em ti. E estão bem. Podem mudar.',
      'Inspira... e traz compaixão para essa criança.',
      'Ela fez o melhor que sabia com o que tinha.',
      'Agora, tu podes escolher diferente. Com gentileza. Sem violência.',
      'A mudança alimentar que dura nasce do amor próprio. Não da punição.',
      'Pergunta a ti: quando como, estou a nutrir-me ou a punir-me?',
      'Deixa a resposta surgir. Sem julgamento.',
      'Hoje, uma escolha com amor. Só uma. É suficiente.',
    ],
  },
  {
    id: 'enraizado_terra',
    nome: 'Enraizado na Terra',
    descricao: 'Meditação de enraizamento para quando te sentes ansioso, disperso ou desligado do teu corpo.',
    duracao_min: 7,
    categoria: 'meditacao',
    icone: '🌍',
    drone: 'vitalis-drone.mp3',
    script: [
      'Senta-te com os pés bem apoiados no chão. Coluna direita.',
      'Fecha os olhos.',
      'Sente o peso do teu corpo. A gravidade a puxá-te suavemente para baixo.',
      'Isso é bom. Significa que estás aqui. Presente.',
      'Inspira devagar... e imagina que as tuas raízes descem pelos pés.',
      'Atravessam o chão. A pedra. A terra.',
      'Chegam ao centro da terra, quente e estável.',
      'Essa terra não se move com o vento. Com as notícias. Com o stress.',
      'Ela simplesmente é. Sempre foi.',
      'E tu és parte dela.',
      'O teu corpo é feito de elementos da terra. Minerais. Água. Carbono.',
      'Quando estás desligado, és como uma árvore sem raízes.',
      'Mas as raízes estão sempre lá. Só precisas de te lembrar.',
      'Respira e sente a firmeza debaixo de ti.',
      'Tudo o que é urgente pode esperar um momento.',
      'Estás seguro. Estás aqui. Estás inteiro.',
      'Abre os olhos devagar. Leva este chão contigo.',
    ],
  },
  {
    id: 'corpo_sagrado',
    nome: 'O Meu Corpo É Sagrado',
    descricao: 'Afirmações para reconstruir uma relação de respeito e cuidado com o teu corpo.',
    duracao_min: 3,
    categoria: 'afirmacoes',
    icone: '✨',
    drone: 'vitalis-drone.mp3',
    script: [
      'Repete estas afirmações. Deixa cada palavra pousar.',
      'O meu corpo merece cuidado, não punição.',
      'Eu alimento-me para me nutrir, não para me castigar.',
      'Cada refeição é uma oportunidade de me respeitar.',
      'O meu corpo é sábio. Ele sabe do que precisa.',
      'Eu ouço a fome real. Não confundo emoção com fome.',
      'O meu corpo não é um problema a resolver. É uma casa a habitar.',
      'Eu movo o meu corpo com prazer, não com obrigação.',
      'A água que bebo nutre cada célula do meu ser.',
      'Eu durmo o suficiente porque me respeito.',
      'O meu peso não define o meu valor.',
      'Eu sou mais do que um número na balança.',
      'Hoje, escolho tratar o meu corpo como algo precioso. Porque é.',
    ],
  },
  {
    id: 'nutrir_amor',
    nome: 'Nutrir com Amor',
    descricao: 'Afirmações para os dias em que a alimentação saudável parece difícil ou sem motivação.',
    duracao_min: 3,
    categoria: 'afirmacoes',
    icone: '💚',
    drone: 'vitalis-drone.mp3',
    script: [
      'Hoje pode não ser perfeito. Está bem.',
      'Uma escolha melhor já é progresso.',
      'Eu não preciso de ser perfeito para estar a avançar.',
      'Cada vez que escolho nutrir-me, estou a investir em mim.',
      'A consistência importa mais do que a perfeição.',
      'Errar numa refeição não apaga tudo o que já fiz.',
      'Começo de novo. Sempre que precisar.',
      'Eu mereço sentir-me bem no meu corpo.',
      'A saúde é um acto de amor, não de controlo.',
      'Eu faço o melhor que posso com o que tenho hoje.',
      'E isso é suficiente. Eu sou suficiente.',
    ],
  },
]
