/**
 * ECOA — Scripts de Meditação e Afirmações
 * Chakra: Vishuddha (Garganta) — 741Hz
 * Tema: Voz, Expressão, Silêncio, Verdade
 *
 * Formato: array de strings — cada item = uma "unidade de respiração"
 * Compatível com ElevenLabs TTS + drone ecoa-drone.mp3 como fundo
 */

export const MEDITACOES_ECOA = [
  {
    id: 'silencio_que_guardas',
    nome: 'O Silêncio Que Guardas',
    descricao: 'Meditação para explorar com compaixão os silêncios que carregas e o que eles protegem.',
    duracao_min: 9,
    categoria: 'meditacao',
    icone: '🤫',
    drone: 'ecoa-drone.mp3',
    script: [
      'Fecha os olhos. Respira fundo três vezes.',
      'Deixa os ombros descerem. A mandíbula relaxar.',
      'Quantas vezes hoje guardaste silêncio quando querias falar?',
      'Não para te julgar. Para perceber.',
      'Pensa numa situação recente em que te calaste.',
      'O que estava lá? Que palavras ficaram por dizer?',
      'Talvez fosse uma opinião que achavas que não ia ser bem recebida.',
      'Talvez um sentimento que pareceu grande demais para ser dito.',
      'Talvez uma necessidade que tinhas vergonha de expressar.',
      'O teu silêncio aprendeu a proteger-te.',
      'Houve momentos em que falar era perigoso. Em que a tua voz foi ignorada ou criticada.',
      'O silêncio foi a tua armadura.',
      'Mas agora, podes perguntar: ainda preciso desta armadura aqui?',
      'Imagina essas palavras por dizer como luz dentro do teu peito.',
      'Não precisas de as soltar agora. Só de as reconhecer.',
      'Elas estão cá. São tuas. E são válidas.',
      'Quando estiveres pronto, abre os olhos. A tua voz existe, mesmo quando está em silêncio.',
    ],
  },
  {
    id: 'voz_valida',
    nome: 'A Tua Voz É Válida',
    descricao: 'Meditação para reconectar com o direito de falar, ocupar espaço e ser ouvido.',
    duracao_min: 8,
    categoria: 'meditacao',
    icone: '🗣️',
    drone: 'ecoa-drone.mp3',
    script: [
      'Senta-te com a coluna direita. Coloca uma mão sobre a garganta.',
      'Sente o calor da tua própria mão.',
      'Respira para esse espaço. Suavemente.',
      'A tua voz não é apenas o som que produces.',
      'É a tua perspectiva. A tua experiência. A tua verdade.',
      'Quantas vezes te ensinaram que ela não importava?',
      'Que eras demasiado sensível. Demasiado directo. Demasiado intenso.',
      'Que era melhor ficar quieto para não criar conflito.',
      'Essas mensagens ficaram. Mas não são factos.',
      'São medos de outras pessoas que te foram transmitidos.',
      'A tua voz tem o mesmo direito de existir que qualquer outra.',
      'Não precisas de a justificar. Não precisas de a suavizar até desaparecer.',
      'Podes falar e estar errado. E isso está bem.',
      'Podes falar e não ser concordado. E isso está bem.',
      'O acto de falar já é um acto de presença.',
      'Inspira. E ao expirar, sente essa permissão a instalar-se.',
      'A tua voz é válida. Sempre foi.',
    ],
  },
  {
    id: 'libertar_a_palavra',
    nome: 'Libertar a Palavra',
    descricao: 'Meditação guiada para soltar palavras que ficaram presas — com gentileza e sem pressa.',
    duracao_min: 10,
    categoria: 'meditacao',
    icone: '🕊️',
    drone: 'ecoa-drone.mp3',
    script: [
      'Encontra uma posição confortável. Fecha os olhos.',
      'Respira devagar. Sem pressa.',
      'Pensa numa coisa que nunca disseste a alguém.',
      'Pode ser uma gratidão. Uma mágoa. Uma verdade. Um pedido de desculpa.',
      'Não a pessoa. Só a coisa que ficou por dizer.',
      'Onde é que sentes isso no teu corpo?',
      'No peito? Na garganta? No estômago?',
      'Fica lá por um momento. Sem tentar mudar.',
      'Agora imagina que podes dizer essa coisa, em segurança, aqui.',
      'Não há consequências. Não há julgamento. Só tu e as tuas palavras.',
      'Deixa as palavras formarem-se... mesmo que imperfeitas...',
      'Talvez não sejam palavras. Talvez sejam imagens. Ou sentimentos.',
      'Observa o que emerge quando podes finalmente soltar.',
      'Nota como o teu corpo responde.',
      'Às vezes libertar uma palavra muda o peso de anos.',
      'Tu não tens de guardar para sempre o que não te pertence.',
      'Inspira profundamente. E ao expirar, solta mais um pouco.',
      'Quando abrires os olhos, leva contigo a leveza deste momento.',
    ],
  },
  {
    id: 'manifesto_da_voz',
    nome: 'Manifesto da Voz',
    descricao: 'Afirmações para reafirmar o teu direito de falar, de ocupar espaço e de ser ouvido.',
    duracao_min: 4,
    categoria: 'afirmacoes',
    icone: '🔊',
    drone: 'ecoa-drone.mp3',
    script: [
      'Estas afirmações são para repetires. Em voz alta sempre que conseguires.',
      'A minha voz merece ser ouvida.',
      'Tenho o direito de me expressar sem me justificar.',
      'O que sinto é real e merece ser comunicado.',
      'Posso dizer não com clareza e sem culpa.',
      'Posso dizer sim com entusiasmo e sem vergonha.',
      'A minha perspectiva tem valor, mesmo quando difere das outras.',
      'Não preciso de esperar permissão para falar.',
      'Posso falar com imperfeição e ainda assim ser válido.',
      'Quanto mais me expresso, mais conheço quem sou.',
      'A minha voz é uma forma de presença no mundo.',
      'Hoje, escolho falar pelo menos uma verdade.',
      'A minha voz pertence-me. E eu deixo-a existir.',
    ],
  },
  {
    id: 'sussurros_coragem',
    nome: 'Sussurros de Coragem',
    descricao: 'Afirmações para os momentos em que tens medo de falar, de ser julgado ou de decepcionar.',
    duracao_min: 3,
    categoria: 'afirmacoes',
    icone: '🌊',
    drone: 'ecoa-drone.mp3',
    script: [
      'Tens medo de falar. Esse medo é real. E não te define.',
      'Eu posso sentir medo e ainda assim dizer a minha verdade.',
      'Não preciso de ser perfeito para ser ouvido.',
      'Falar com voz trêmula ainda é falar.',
      'O desconforto de me expressar é menor do que o peso do silêncio.',
      'Não sou responsável pela reacção dos outros à minha verdade.',
      'Posso decepcionar alguém e ainda assim estar a fazer o certo.',
      'A minha necessidade de ser autêntico é mais importante do que ser aprovado.',
      'Cada vez que falo verdade, fortaleço a minha voz.',
      'A coragem não é falar sem medo. É falar apesar dele.',
      'A minha voz cresce cada vez que a uso.',
    ],
  },
]
