import { Recipe } from "./types";

export const SAMPLE_RECIPES: Recipe[] = [
  // 1. Matapa — safe for both
  {
    id: "recipe-1",
    household_id: "h1",
    name: "Matapa",
    category: "Prato principal",
    cuisine: "Moçambicana",
    tags: ["Moçambicana", "Sem Leite", "Sem Trigo", "Sem Ovos"],
    prep_time_min: 60,
    servings: 4,
    difficulty: "Médio",
    ingredients: [
      { name: "Folhas de mandioca (ou espinafres)", qty: 500, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Amendoim torrado moído", qty: 200, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Camarão seco", qty: 100, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Leite de coco", qty: 400, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Alho picado", qty: 3, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Cebola picada", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sal", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Lavar bem as folhas de mandioca e picar finamente.",
      "Cozer as folhas em água com sal durante 30 minutos até ficarem macias.",
      "Num pilão ou processador, triturar o amendoim até obter uma pasta.",
      "Juntar a pasta de amendoim, o camarão seco, o alho e a cebola às folhas cozidas.",
      "Adicionar o leite de coco e deixar cozinhar em lume brando por 20 minutos, mexendo regularmente.",
      "Servir quente com arroz branco.",
    ],
    notes: "Prato tradicional moçambicano. Pode substituir as folhas de mandioca por espinafres para preparação mais rápida.",
    photo_url: null,
    youtube_videos: null,
    is_favorite: false,
    is_vivianne_safe: true,
    is_ticy_safe: true,
    times_used: 3,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "vivianne",
    created_at: "2026-01-15T10:00:00Z",
  },

  // 2. Caril de Frango — safe for both
  {
    id: "recipe-2",
    household_id: "h1",
    name: "Caril de Frango",
    category: "Prato principal",
    cuisine: "Moçambicana",
    tags: ["Moçambicana", "Sem Leite", "Sem Trigo", "Sem Ovos"],
    prep_time_min: 45,
    servings: 4,
    difficulty: "Fácil",
    ingredients: [
      { name: "Coxas de frango", qty: 800, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Leite de coco", qty: 400, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Cebola picada", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Tomate maduro picado", qty: 3, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Caril em pó", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Alho picado", qty: 3, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Óleo vegetal", qty: 30, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Piri-piri (opcional)", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sal e pimenta", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Temperar o frango com sal, pimenta e metade do caril. Deixar marinar 15 minutos.",
      "Aquecer o óleo numa panela e dourar o frango de ambos os lados. Reservar.",
      "Na mesma panela, refogar a cebola e o alho até ficarem dourados.",
      "Juntar o tomate picado e o restante caril. Cozinhar 5 minutos.",
      "Devolver o frango à panela, adicionar o leite de coco e o piri-piri.",
      "Deixar cozinhar em lume brando por 25 minutos. Servir com arroz.",
    ],
    notes: "O piri-piri é opcional — ajustar ao gosto da família.",
    photo_url: null,
    youtube_videos: null,
    is_favorite: true,
    is_vivianne_safe: true,
    is_ticy_safe: true,
    times_used: 5,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "vivianne",
    created_at: "2026-01-20T10:00:00Z",
  },

  // 3. Frango Assado com Batatas — safe for both
  {
    id: "recipe-3",
    household_id: "h1",
    name: "Frango Assado com Batatas",
    category: "Prato principal",
    cuisine: "Portuguesa",
    tags: ["Portuguesa", "Sem Leite", "Sem Trigo", "Sem Ovos"],
    prep_time_min: 75,
    servings: 4,
    difficulty: "Fácil",
    ingredients: [
      { name: "Frango inteiro", qty: 1.5, unit: "kg", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Batatas cortadas em quartos", qty: 800, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Azeite", qty: 60, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Alho picado", qty: 4, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sumo de limão", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Pimentão doce", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sal e pimenta", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Pré-aquecer o forno a 200°C.",
      "Temperar o frango com azeite, alho, limão, pimentão, sal e pimenta.",
      "Colocar o frango num tabuleiro com as batatas à volta, regadas com azeite.",
      "Assar no forno durante 1 hora, regando com o molho a cada 20 minutos.",
      "O frango está pronto quando a pele estiver dourada e o sumo sair claro.",
    ],
    notes: null,
    photo_url: null,
    youtube_videos: null,
    is_favorite: false,
    is_vivianne_safe: true,
    is_ticy_safe: true,
    times_used: 2,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "vivianne",
    created_at: "2026-02-01T10:00:00Z",
  },

  // 4. Bacalhau à Brás — has eggs + wheat: not safe for Vivianne or Ticy
  {
    id: "recipe-4",
    household_id: "h1",
    name: "Bacalhau à Brás",
    category: "Prato principal",
    cuisine: "Portuguesa",
    tags: ["Portuguesa", "Comfort Food"],
    prep_time_min: 40,
    servings: 4,
    difficulty: "Médio",
    ingredients: [
      { name: "Bacalhau desfiado (demolhado)", qty: 400, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Batata palha fina", qty: 200, unit: "g", is_allergen_milk: false, is_allergen_wheat: true, is_allergen_egg: false },
      { name: "Ovos", qty: 6, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: true },
      { name: "Cebola cortada em meias-luas", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Alho picado", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Azeite", qty: 60, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Azeitonas pretas", qty: 50, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Salsa picada", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sal e pimenta", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Refogar a cebola e o alho em azeite até ficarem macios.",
      "Juntar o bacalhau desfiado e deixar cozinhar 5 minutos.",
      "Adicionar a batata palha e envolver bem.",
      "Bater os ovos e juntar à mistura, mexendo rapidamente em lume brando até os ovos ficarem cremosos (não secos).",
      "Decorar com azeitonas e salsa picada. Servir imediatamente.",
    ],
    notes: "O segredo é não deixar os ovos cozinharem demasiado — devem ficar cremosos.",
    photo_url: null,
    youtube_videos: null,
    is_favorite: true,
    is_vivianne_safe: false,
    is_ticy_safe: false,
    times_used: 4,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "ticy",
    created_at: "2026-02-05T10:00:00Z",
  },

  // 5. Stir-fry de Frango — safe for both
  {
    id: "recipe-5",
    household_id: "h1",
    name: "Stir-fry de Frango com Legumes",
    category: "Prato principal",
    cuisine: "Asiática",
    tags: ["Internacional", "Rápida", "Sem Leite", "Sem Trigo", "Sem Ovos"],
    prep_time_min: 20,
    servings: 3,
    difficulty: "Fácil",
    ingredients: [
      { name: "Peito de frango em tiras", qty: 400, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Brócolos em floretes", qty: 200, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Cenoura em palitos", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Pimento vermelho em tiras", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Molho de soja (tamari sem glúten)", qty: 30, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Gengibre fresco ralado", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Alho picado", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Óleo de sésamo", qty: 15, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Aquecer o óleo de sésamo numa wok ou frigideira grande em lume alto.",
      "Saltear o frango em tiras até dourar, cerca de 4 minutos. Reservar.",
      "Na mesma wok, saltear os legumes por 3 minutos (devem ficar crocantes).",
      "Devolver o frango, juntar o alho, gengibre e molho de soja.",
      "Mexer tudo por 1 minuto. Servir com arroz basmati.",
    ],
    notes: "Usar tamari em vez de molho de soja normal para garantir que é sem trigo.",
    photo_url: null,
    youtube_videos: null,
    is_favorite: false,
    is_vivianne_safe: true,
    is_ticy_safe: true,
    times_used: 1,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "vivianne",
    created_at: "2026-02-10T10:00:00Z",
  },

  // 6. Risotto de Cogumelos — has milk (butter/cheese): not safe for Vivianne
  {
    id: "recipe-6",
    household_id: "h1",
    name: "Risotto de Cogumelos",
    category: "Prato principal",
    cuisine: "Italiana",
    tags: ["Internacional", "Comfort Food", "Sem Ovos"],
    prep_time_min: 40,
    servings: 4,
    difficulty: "Médio",
    ingredients: [
      { name: "Arroz arbóreo", qty: 300, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Cogumelos variados fatiados", qty: 300, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Caldo de legumes quente", qty: 1, unit: "litro", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Cebola picada", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Vinho branco", qty: 100, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Manteiga", qty: 40, unit: "g", is_allergen_milk: true, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Queijo parmesão ralado", qty: 60, unit: "g", is_allergen_milk: true, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Azeite", qty: 30, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sal e pimenta", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Refogar a cebola em azeite até ficar transparente.",
      "Juntar os cogumelos e saltear até ficarem dourados, cerca de 5 minutos.",
      "Adicionar o arroz e mexer por 2 minutos até ficar translúcido.",
      "Adicionar o vinho branco e mexer até evaporar.",
      "Ir adicionando o caldo quente, uma concha de cada vez, mexendo continuamente até o arroz absorver o líquido (20 minutos).",
      "Retirar do lume, juntar a manteiga e o parmesão. Servir imediatamente.",
    ],
    notes: "Para versão da Vivianne: substituir manteiga por azeite e omitir o parmesão.",
    photo_url: null,
    youtube_videos: null,
    is_favorite: false,
    is_vivianne_safe: false,
    is_ticy_safe: true,
    times_used: 2,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "ticy",
    created_at: "2026-02-15T10:00:00Z",
  },

  // 7. Omeleta de Legumes — has eggs: not safe for Ticy, safe for Vivianne
  {
    id: "recipe-7",
    household_id: "h1",
    name: "Omeleta de Legumes",
    category: "Prato principal",
    cuisine: "Portuguesa",
    tags: ["Rápida", "Low Carb", "Sem Leite", "Sem Trigo"],
    prep_time_min: 15,
    servings: 2,
    difficulty: "Fácil",
    ingredients: [
      { name: "Ovos", qty: 4, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: true },
      { name: "Espinafres frescos", qty: 100, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Tomate cherry cortado ao meio", qty: 100, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Cebola picada", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Azeite", qty: 15, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sal e pimenta", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Bater os ovos com sal e pimenta.",
      "Refogar a cebola em azeite até ficar macia. Juntar os espinafres e os tomates cherry.",
      "Verter os ovos batidos por cima e cozinhar em lume médio-baixo.",
      "Quando a base estiver firme, dobrar ao meio e servir.",
    ],
    notes: "Boa opção low carb para a Vivianne. Ticy pode comer outra opção.",
    photo_url: null,
    youtube_videos: null,
    is_favorite: false,
    is_vivianne_safe: true,
    is_ticy_safe: false,
    times_used: 6,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "vivianne",
    created_at: "2026-02-20T10:00:00Z",
  },

  // 8. Bife Grelhado com Salada — safe for both
  {
    id: "recipe-8",
    household_id: "h1",
    name: "Bife Grelhado com Salada",
    category: "Prato principal",
    cuisine: "Portuguesa",
    tags: ["Rápida", "Low Carb", "Sem Leite", "Sem Trigo", "Sem Ovos"],
    prep_time_min: 20,
    servings: 2,
    difficulty: "Fácil",
    ingredients: [
      { name: "Bifes de vaca (alcatra ou lombo)", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Alface variada", qty: 150, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Tomate", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Pepino", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Azeite", qty: 30, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sumo de limão", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Alho picado", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sal e pimenta", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Temperar os bifes com alho, azeite, sal e pimenta. Deixar marinar 10 minutos.",
      "Aquecer uma frigideira ou grelha em lume alto.",
      "Grelhar os bifes 3-4 minutos de cada lado (ao ponto médio).",
      "Preparar a salada com alface, tomate e pepino. Temperar com azeite e limão.",
      "Servir os bifes com a salada ao lado.",
    ],
    notes: null,
    photo_url: null,
    youtube_videos: null,
    is_favorite: false,
    is_vivianne_safe: true,
    is_ticy_safe: true,
    times_used: 3,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "ticy",
    created_at: "2026-03-01T10:00:00Z",
  },
  {
    id: "recipe-9",
    household_id: "h1",
    name: "Caril de Camarão",
    category: "Prato principal",
    cuisine: "Moçambicana",
    tags: ["Moçambicana", "Sem Leite", "Sem Trigo", "Sem Ovos"],
    prep_time_min: 35,
    servings: 5,
    difficulty: "Médio",
    ingredients: [
      { name: "Camarão descascado", qty: 500, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Leite de coco", qty: 400, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Tomate maduro", qty: 3, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Cebola picada", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Alho picado", qty: 3, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Pimentão doce", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Óleo vegetal", qty: 30, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sal e pimenta", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Descascar e limpar o camarão.",
      "Refogar a cebola e o alho em óleo até ficarem dourados.",
      "Juntar o tomate picado e o pimentão. Cozinhar 5 minutos.",
      "Adicionar o leite de coco e deixar ferver.",
      "Juntar o camarão e cozinhar 5 minutos até ficar rosado.",
      "Servir com arroz branco.",
    ],
    notes: null,
    photo_url: null,
    youtube_videos: null,
    is_favorite: false,
    is_vivianne_safe: true,
    is_ticy_safe: true,
    times_used: 3,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "vivianne",
    created_at: "2026-03-02T10:00:00Z",
  },

  {
    id: "recipe-10",
    household_id: "h1",
    name: "Galinha à Zambeziana",
    category: "Prato principal",
    cuisine: "Moçambicana",
    tags: ["Moçambicana", "Sem Leite", "Sem Trigo", "Sem Ovos"],
    prep_time_min: 50,
    servings: 5,
    difficulty: "Médio",
    ingredients: [
      { name: "Frango em peças", qty: 1000, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Amendoim moído", qty: 150, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Leite de coco", qty: 400, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Cebola picada", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Alho picado", qty: 3, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sumo de limão", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Piri-piri", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sal", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Temperar o frango com limão, alho e sal. Marinar 15 minutos.",
      "Dourar o frango em óleo numa panela grande.",
      "Refogar a cebola até ficar macia.",
      "Juntar o amendoim moído e o leite de coco.",
      "Cozinhar em lume brando por 30 minutos.",
      "Servir com xima ou arroz.",
    ],
    notes: null,
    photo_url: null,
    youtube_videos: null,
    is_favorite: true,
    is_vivianne_safe: true,
    is_ticy_safe: true,
    times_used: 4,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "vivianne",
    created_at: "2026-03-03T10:00:00Z",
  },

  {
    id: "recipe-11",
    household_id: "h1",
    name: "Chambo na Brasa",
    category: "Prato principal",
    cuisine: "Moçambicana",
    tags: ["Moçambicana", "Sem Leite", "Sem Trigo", "Sem Ovos"],
    prep_time_min: 30,
    servings: 5,
    difficulty: "Fácil",
    ingredients: [
      { name: "Chambo ou tilápia inteiro", qty: 4, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Limão", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Alho picado", qty: 4, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Piri-piri fresco", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Azeite", qty: 40, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sal grosso", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Limpar o peixe e fazer cortes diagonais na pele.",
      "Temperar com limão, alho, piri-piri e sal. Marinar 15 minutos.",
      "Grelhar na brasa ou grelha quente, 7 minutos de cada lado.",
      "Servir com salada fresca e limão.",
    ],
    notes: "Peixe típico moçambicano. Pode usar tilápia se não encontrar chambo.",
    photo_url: null,
    youtube_videos: null,
    is_favorite: false,
    is_vivianne_safe: true,
    is_ticy_safe: true,
    times_used: 2,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "vivianne",
    created_at: "2026-03-04T10:00:00Z",
  },

  {
    id: "recipe-12",
    household_id: "h1",
    name: "Feijão com Coco",
    category: "Prato principal",
    cuisine: "Moçambicana",
    tags: ["Moçambicana", "Sem Leite", "Sem Trigo", "Sem Ovos"],
    prep_time_min: 45,
    servings: 5,
    difficulty: "Fácil",
    ingredients: [
      { name: "Feijão manteiga", qty: 400, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Leite de coco", qty: 400, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Cebola picada", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Tomate maduro", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Alho picado", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Óleo vegetal", qty: 30, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sal", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Demolhar o feijão de véspera. Cozer em água com sal até ficar macio (30 minutos).",
      "Refogar a cebola e o alho em óleo.",
      "Juntar o tomate picado e cozinhar 5 minutos.",
      "Adicionar o feijão cozido e o leite de coco.",
      "Cozinhar em lume brando por 15 minutos. Servir com arroz.",
    ],
    notes: null,
    photo_url: null,
    youtube_videos: null,
    is_favorite: false,
    is_vivianne_safe: true,
    is_ticy_safe: true,
    times_used: 2,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "vivianne",
    created_at: "2026-03-05T10:00:00Z",
  },

  {
    id: "recipe-13",
    household_id: "h1",
    name: "Xima",
    category: "Acompanhamento",
    cuisine: "Moçambicana",
    tags: ["Moçambicana", "Sem Leite", "Sem Trigo", "Sem Ovos"],
    prep_time_min: 15,
    servings: 5,
    difficulty: "Fácil",
    ingredients: [
      { name: "Farinha de milho", qty: 500, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Água", qty: 1, unit: "litro", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sal", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Ferver a água com uma pitada de sal.",
      "Adicionar a farinha de milho aos poucos, mexendo sem parar.",
      "Mexer vigorosamente com colher de pau durante 10 minutos até ficar consistente.",
      "Formar uma bola e servir como acompanhamento de caril ou matapa.",
    ],
    notes: "Acompanhamento tradicional moçambicano. A consistência ideal é firme mas não seca.",
    photo_url: null,
    youtube_videos: null,
    is_favorite: false,
    is_vivianne_safe: true,
    is_ticy_safe: true,
    times_used: 5,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "vivianne",
    created_at: "2026-03-06T10:00:00Z",
  },

  {
    id: "recipe-14",
    household_id: "h1",
    name: "Mucapata",
    category: "Prato principal",
    cuisine: "Moçambicana",
    tags: ["Moçambicana", "Sem Leite", "Sem Trigo", "Sem Ovos"],
    prep_time_min: 50,
    servings: 5,
    difficulty: "Médio",
    ingredients: [
      { name: "Feijão nhemba", qty: 400, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Amendoim torrado", qty: 150, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Cebola picada", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Alho picado", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Óleo vegetal", qty: 30, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sal", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Cozer o feijão nhemba em água até ficar macio.",
      "Triturar o amendoim até obter uma pasta grossa.",
      "Refogar a cebola e o alho em óleo.",
      "Juntar o feijão cozido e a pasta de amendoim.",
      "Cozinhar em lume brando por 15 minutos, mexendo. Servir com arroz.",
    ],
    notes: null,
    photo_url: null,
    youtube_videos: null,
    is_favorite: false,
    is_vivianne_safe: true,
    is_ticy_safe: true,
    times_used: 1,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "vivianne",
    created_at: "2026-03-07T10:00:00Z",
  },

  {
    id: "recipe-15",
    household_id: "h1",
    name: "Caldo Verde",
    category: "Sopa",
    cuisine: "Portuguesa",
    tags: ["Portuguesa", "Sem Leite", "Sem Trigo", "Sem Ovos"],
    prep_time_min: 30,
    servings: 5,
    difficulty: "Fácil",
    ingredients: [
      { name: "Batatas", qty: 500, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Couve portuguesa", qty: 200, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Chouriço", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Cebola", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Alho picado", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Azeite", qty: 40, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sal", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Cozer as batatas com a cebola e o alho em água com sal.",
      "Triturar com varinha mágica até obter um creme.",
      "Cortar a couve em tiras muito finas.",
      "Adicionar a couve ao creme e cozinhar 10 minutos.",
      "Servir com rodelas de chouriço e um fio de azeite.",
    ],
    notes: null,
    photo_url: null,
    youtube_videos: null,
    is_favorite: false,
    is_vivianne_safe: true,
    is_ticy_safe: true,
    times_used: 3,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "vivianne",
    created_at: "2026-03-08T10:00:00Z",
  },

  {
    id: "recipe-16",
    household_id: "h1",
    name: "Caldeirada de Peixe",
    category: "Prato principal",
    cuisine: "Portuguesa",
    tags: ["Portuguesa", "Sem Leite", "Sem Trigo", "Sem Ovos"],
    prep_time_min: 45,
    servings: 5,
    difficulty: "Médio",
    ingredients: [
      { name: "Peixe misto em postas", qty: 800, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Batatas fatiadas", qty: 400, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Tomate maduro", qty: 3, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Cebola em rodelas", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Pimento verde", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Azeite", qty: 60, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Salsa picada", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sal e pimenta", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Dispor camadas no fundo da panela: batatas, cebola, tomate, pimento.",
      "Colocar o peixe por cima e repetir as camadas.",
      "Regar com azeite e temperar com sal.",
      "Tapar e cozinhar em lume brando por 40 minutos sem mexer.",
      "Polvilhar com salsa e servir na panela.",
    ],
    notes: null,
    photo_url: null,
    youtube_videos: null,
    is_favorite: false,
    is_vivianne_safe: true,
    is_ticy_safe: true,
    times_used: 2,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "ticy",
    created_at: "2026-03-09T10:00:00Z",
  },

  {
    id: "recipe-17",
    household_id: "h1",
    name: "Bifanas",
    category: "Prato principal",
    cuisine: "Portuguesa",
    tags: ["Portuguesa"],
    prep_time_min: 20,
    servings: 5,
    difficulty: "Fácil",
    ingredients: [
      { name: "Carne de porco fatiada fina", qty: 600, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Pão bijou", qty: 5, unit: "un", is_allergen_milk: false, is_allergen_wheat: true, is_allergen_egg: false },
      { name: "Alho picado", qty: 4, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Vinho branco", qty: 100, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Pimentão doce", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Azeite", qty: 40, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sal", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Marinar a carne com alho, vinho branco, pimentão e sal durante 1 hora.",
      "Aquecer uma frigideira em lume alto e frigir a carne rapidamente.",
      "Abrir os pães e rechear com a carne.",
      "Regar com o molho da frigideira e servir.",
    ],
    notes: "Vivianne pode comer a carne sem o pão.",
    photo_url: null,
    youtube_videos: null,
    is_favorite: false,
    is_vivianne_safe: false,
    is_ticy_safe: true,
    times_used: 2,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "ticy",
    created_at: "2026-03-10T10:00:00Z",
  },

  {
    id: "recipe-18",
    household_id: "h1",
    name: "Arroz de Marisco",
    category: "Prato principal",
    cuisine: "Portuguesa",
    tags: ["Portuguesa", "Sem Leite", "Sem Trigo", "Sem Ovos"],
    prep_time_min: 40,
    servings: 5,
    difficulty: "Médio",
    ingredients: [
      { name: "Camarão", qty: 300, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Mexilhão", qty: 300, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Arroz", qty: 400, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Tomate maduro", qty: 3, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Cebola picada", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Alho picado", qty: 3, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Azeite", qty: 40, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Coentros frescos", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sal e pimenta", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Refogar cebola e alho em azeite.",
      "Juntar o tomate picado e cozinhar 5 minutos.",
      "Adicionar o arroz e o caldo de peixe. Cozinhar 15 minutos.",
      "Juntar o marisco e cozinhar mais 5 minutos até abrir os mexilhões.",
      "Polvilhar com coentros e servir.",
    ],
    notes: null,
    photo_url: null,
    youtube_videos: null,
    is_favorite: true,
    is_vivianne_safe: true,
    is_ticy_safe: true,
    times_used: 3,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "vivianne",
    created_at: "2026-03-11T10:00:00Z",
  },

  {
    id: "recipe-19",
    household_id: "h1",
    name: "Curry Thai de Camarão",
    category: "Prato principal",
    cuisine: "Asiática",
    tags: ["Internacional", "Sem Leite", "Sem Trigo", "Sem Ovos"],
    prep_time_min: 25,
    servings: 5,
    difficulty: "Fácil",
    ingredients: [
      { name: "Camarão", qty: 500, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Leite de coco", qty: 400, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Pasta de curry vermelho", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Pimento vermelho", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Courgette", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Manjericão fresco", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Óleo vegetal", qty: 15, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sal", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Aquecer o óleo e fritar a pasta de curry por 1 minuto.",
      "Adicionar o leite de coco e deixar ferver.",
      "Juntar os legumes cortados e cozinhar 5 minutos.",
      "Adicionar o camarão e cozinhar 3 minutos.",
      "Juntar o manjericão fresco e servir com arroz.",
    ],
    notes: null,
    photo_url: null,
    youtube_videos: null,
    is_favorite: false,
    is_vivianne_safe: true,
    is_ticy_safe: true,
    times_used: 1,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "vivianne",
    created_at: "2026-03-12T10:00:00Z",
  },

  {
    id: "recipe-20",
    household_id: "h1",
    name: "Noodles Salteados com Frango",
    category: "Prato principal",
    cuisine: "Asiática",
    tags: ["Internacional", "Rápida"],
    prep_time_min: 20,
    servings: 4,
    difficulty: "Fácil",
    ingredients: [
      { name: "Noodles de trigo", qty: 300, unit: "g", is_allergen_milk: false, is_allergen_wheat: true, is_allergen_egg: false },
      { name: "Peito de frango em tiras", qty: 400, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Pimento vermelho", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Cenoura em palitos", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Molho de soja", qty: 30, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Gengibre ralado", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Óleo de sésamo", qty: 15, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sal", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Cozer os noodles al dente e escorrer.",
      "Saltear o frango em óleo de sésamo até dourar.",
      "Juntar os legumes e saltear 3 minutos.",
      "Adicionar os noodles e o molho de soja.",
      "Mexer tudo e servir quente.",
    ],
    notes: "Alternativa para Vivianne: usar noodles de arroz em vez de trigo.",
    photo_url: null,
    youtube_videos: null,
    is_favorite: false,
    is_vivianne_safe: false,
    is_ticy_safe: true,
    times_used: 2,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "ticy",
    created_at: "2026-03-13T10:00:00Z",
  },

  {
    id: "recipe-21",
    household_id: "h1",
    name: "Pizza Caseira",
    category: "Prato principal",
    cuisine: "Italiana",
    tags: ["Internacional", "Comfort Food"],
    prep_time_min: 45,
    servings: 5,
    difficulty: "Médio",
    ingredients: [
      { name: "Farinha de trigo", qty: 400, unit: "g", is_allergen_milk: false, is_allergen_wheat: true, is_allergen_egg: false },
      { name: "Fermento seco", qty: 7, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Mozzarella", qty: 200, unit: "g", is_allergen_milk: true, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Molho de tomate", qty: 200, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Azeite", qty: 30, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sal", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Misturar farinha, fermento, água morna, azeite e sal. Amassar 10 minutos.",
      "Deixar a massa levedar 30 minutos coberta.",
      "Esticar a massa num tabuleiro untado.",
      "Cobrir com molho de tomate e mozzarella.",
      "Assar a 200°C durante 15 minutos.",
    ],
    notes: "Vivianne não pode comer (trigo + queijo). Fazer alternativa para ela.",
    photo_url: null,
    youtube_videos: null,
    is_favorite: false,
    is_vivianne_safe: false,
    is_ticy_safe: true,
    times_used: 3,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "ticy",
    created_at: "2026-03-14T10:00:00Z",
  },

  {
    id: "recipe-22",
    household_id: "h1",
    name: "Tacos de Carne",
    category: "Prato principal",
    cuisine: null,
    tags: ["Internacional", "Rápida", "Sem Leite", "Sem Trigo", "Sem Ovos"],
    prep_time_min: 25,
    servings: 5,
    difficulty: "Fácil",
    ingredients: [
      { name: "Carne moída", qty: 500, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Tortilhas de milho", qty: 10, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Alface picada", qty: 100, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Tomate picado", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Abacate", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Limão", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Cominhos em pó", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sal e pimenta", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Temperar a carne moída com cominhos, sal e pimenta.",
      "Frigir a carne em lume alto até dourar.",
      "Aquecer as tortilhas de milho.",
      "Montar os tacos: carne, alface, tomate e abacate.",
      "Regar com sumo de limão e servir.",
    ],
    notes: "Tortilhas de milho são seguras para Vivianne (sem trigo).",
    photo_url: null,
    youtube_videos: null,
    is_favorite: false,
    is_vivianne_safe: true,
    is_ticy_safe: true,
    times_used: 2,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "vivianne",
    created_at: "2026-03-15T10:00:00Z",
  },

  {
    id: "recipe-23",
    household_id: "h1",
    name: "Pad Thai",
    category: "Prato principal",
    cuisine: "Asiática",
    tags: ["Internacional", "Sem Leite", "Sem Trigo"],
    prep_time_min: 25,
    servings: 4,
    difficulty: "Médio",
    ingredients: [
      { name: "Noodles de arroz", qty: 300, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Camarão", qty: 200, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Ovos", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: true },
      { name: "Amendoim torrado", qty: 50, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Lima", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Molho de peixe", qty: 30, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Açúcar de palma", qty: 15, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Rebentos de soja", qty: 100, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Demolhar os noodles de arroz em água quente 10 minutos.",
      "Saltear o camarão em óleo quente. Reservar.",
      "Fazer ovo mexido na mesma wok.",
      "Juntar os noodles, molho de peixe e açúcar. Misturar bem.",
      "Adicionar camarão e rebentos. Servir com amendoim e lima.",
    ],
    notes: "Contém ovos — não incluir na lancheira escolar.",
    photo_url: null,
    youtube_videos: null,
    is_favorite: false,
    is_vivianne_safe: true,
    is_ticy_safe: false,
    times_used: 1,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "vivianne",
    created_at: "2026-03-16T10:00:00Z",
  },

  {
    id: "recipe-24",
    household_id: "h1",
    name: "Sopa de Legumes",
    category: "Sopa",
    cuisine: "Portuguesa",
    tags: ["Portuguesa", "Rápida", "Sem Leite", "Sem Trigo", "Sem Ovos"],
    prep_time_min: 30,
    servings: 5,
    difficulty: "Fácil",
    ingredients: [
      { name: "Batata", qty: 3, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Cenoura", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Courgette", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Cebola", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Alho picado", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Azeite", qty: 30, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sal", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Descascar e cortar todos os legumes.",
      "Refogar a cebola e o alho em azeite.",
      "Juntar os restantes legumes e cobrir com água.",
      "Cozinhar 20 minutos até ficarem macios.",
      "Triturar com varinha mágica. Servir com fio de azeite.",
    ],
    notes: null,
    photo_url: null,
    youtube_videos: null,
    is_favorite: false,
    is_vivianne_safe: true,
    is_ticy_safe: true,
    times_used: 4,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "vivianne",
    created_at: "2026-03-17T10:00:00Z",
  },

  {
    id: "recipe-25",
    household_id: "h1",
    name: "Salada de Grão-de-Bico",
    category: "Prato principal",
    cuisine: null,
    tags: ["Rápida", "Sem Leite", "Sem Trigo", "Sem Ovos", "Low Carb"],
    prep_time_min: 15,
    servings: 4,
    difficulty: "Fácil",
    ingredients: [
      { name: "Grão-de-bico cozido", qty: 400, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Tomate", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Pepino", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Cebola roxa", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Salsa fresca", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Azeite", qty: 40, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sumo de limão", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sal e pimenta", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Escorrer o grão-de-bico.",
      "Picar o tomate, pepino e cebola roxa em cubos pequenos.",
      "Misturar tudo numa tigela.",
      "Temperar com azeite, limão, sal e pimenta.",
      "Juntar a salsa picada e servir.",
    ],
    notes: null,
    photo_url: null,
    youtube_videos: null,
    is_favorite: false,
    is_vivianne_safe: true,
    is_ticy_safe: true,
    times_used: 2,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "vivianne",
    created_at: "2026-03-18T10:00:00Z",
  },

  {
    id: "recipe-26",
    household_id: "h1",
    name: "Wraps de Frango",
    category: "Prato principal",
    cuisine: null,
    tags: ["Rápida"],
    prep_time_min: 15,
    servings: 4,
    difficulty: "Fácil",
    ingredients: [
      { name: "Tortilha de trigo", qty: 4, unit: "un", is_allergen_milk: false, is_allergen_wheat: true, is_allergen_egg: false },
      { name: "Peito de frango grelhado", qty: 300, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Alface", qty: 100, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Tomate", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Mostarda", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Azeite", qty: 15, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Grelhar o frango e cortar em tiras.",
      "Aquecer as tortilhas numa frigideira.",
      "Montar os wraps com frango, alface, tomate e mostarda.",
      "Enrolar bem apertado e cortar ao meio.",
    ],
    notes: "Alternativa Vivianne: usar folha de alface em vez de tortilha.",
    photo_url: null,
    youtube_videos: null,
    is_favorite: false,
    is_vivianne_safe: false,
    is_ticy_safe: true,
    times_used: 3,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "ticy",
    created_at: "2026-03-19T10:00:00Z",
  },

  {
    id: "recipe-27",
    household_id: "h1",
    name: "Peixe Grelhado com Vegetais",
    category: "Prato principal",
    cuisine: null,
    tags: ["Rápida", "Sem Leite", "Sem Trigo", "Sem Ovos", "Low Carb"],
    prep_time_min: 25,
    servings: 5,
    difficulty: "Fácil",
    ingredients: [
      { name: "Filetes de peixe", qty: 600, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Brócolos", qty: 200, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Cenoura", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Azeite", qty: 40, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Limão", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Alho picado", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sal e pimenta", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Temperar o peixe com limão, alho, sal e pimenta.",
      "Cozer os brócolos e cenouras ao vapor 8 minutos.",
      "Grelhar o peixe 4 minutos de cada lado.",
      "Servir o peixe com os vegetais, regado com azeite.",
    ],
    notes: null,
    photo_url: null,
    youtube_videos: null,
    is_favorite: false,
    is_vivianne_safe: true,
    is_ticy_safe: true,
    times_used: 3,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "vivianne",
    created_at: "2026-03-20T10:00:00Z",
  },

  {
    id: "recipe-28",
    household_id: "h1",
    name: "Frango com Brócolos ao Vapor",
    category: "Prato principal",
    cuisine: null,
    tags: ["Rápida", "Sem Leite", "Sem Trigo", "Sem Ovos", "Low Carb"],
    prep_time_min: 20,
    servings: 5,
    difficulty: "Fácil",
    ingredients: [
      { name: "Peito de frango", qty: 500, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Brócolos", qty: 400, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Azeite", qty: 30, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Alho picado", qty: 3, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Limão", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sal e pimenta", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Cortar o frango em pedaços e temperar com alho, sal e pimenta.",
      "Grelhar o frango numa frigideira com azeite, 5 minutos de cada lado.",
      "Cozer os brócolos ao vapor durante 6 minutos.",
      "Servir com limão e azeite por cima.",
    ],
    notes: "Opção low carb perfeita.",
    photo_url: null,
    youtube_videos: null,
    is_favorite: false,
    is_vivianne_safe: true,
    is_ticy_safe: true,
    times_used: 4,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "vivianne",
    created_at: "2026-03-21T10:00:00Z",
  },

  {
    id: "recipe-29",
    household_id: "h1",
    name: "Salada de Atum",
    category: "Lancheira",
    cuisine: null,
    tags: ["Rápida", "Sem Leite", "Sem Trigo", "Sem Ovos", "Low Carb"],
    prep_time_min: 10,
    servings: 2,
    difficulty: "Fácil",
    ingredients: [
      { name: "Atum em lata", qty: 2, unit: "lata", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Alface variada", qty: 100, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Tomate cherry", qty: 100, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Pepino", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Azeite", qty: 20, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Limão", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Escorrer o atum.",
      "Cortar a alface, tomates e pepino.",
      "Misturar tudo numa tigela.",
      "Temperar com azeite e limão.",
    ],
    notes: "Perfeita para a lancheira da Vivianne.",
    photo_url: null,
    youtube_videos: null,
    is_favorite: false,
    is_vivianne_safe: true,
    is_ticy_safe: true,
    times_used: 5,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "vivianne",
    created_at: "2026-03-22T10:00:00Z",
  },

  {
    id: "recipe-30",
    household_id: "h1",
    name: "Espetadas de Frango com Legumes",
    category: "Prato principal",
    cuisine: null,
    tags: ["Sem Leite", "Sem Trigo", "Sem Ovos"],
    prep_time_min: 30,
    servings: 5,
    difficulty: "Fácil",
    ingredients: [
      { name: "Peito de frango", qty: 500, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Pimento verde", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Pimento vermelho", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Pimento amarelo", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Cebola", qty: 2, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Azeite", qty: 40, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Pimentão doce", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sal e pimenta", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Cortar o frango e os legumes em cubos grandes.",
      "Temperar o frango com azeite, pimentão, sal e pimenta.",
      "Montar as espetadas alternando frango e legumes.",
      "Grelhar 10 minutos, virando regularmente.",
    ],
    notes: null,
    photo_url: null,
    youtube_videos: null,
    is_favorite: false,
    is_vivianne_safe: true,
    is_ticy_safe: true,
    times_used: 2,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "vivianne",
    created_at: "2026-03-23T10:00:00Z",
  },

  {
    id: "recipe-31",
    household_id: "h1",
    name: "Panquecas de Banana e Aveia",
    category: "Lancheira",
    cuisine: null,
    tags: ["Sem Leite", "Sem Trigo"],
    prep_time_min: 15,
    servings: 4,
    difficulty: "Fácil",
    ingredients: [
      { name: "Banana madura", qty: 3, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Aveia em flocos", qty: 200, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Ovos", qty: 3, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: true },
      { name: "Canela em pó", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Mel", qty: 30, unit: "ml", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Esmagar as bananas com um garfo.",
      "Misturar com a aveia, ovos e canela.",
      "Frigir porções pequenas em frigideira antiaderente.",
      "Servir com mel por cima.",
    ],
    notes: "Atenção: contém ovos — não incluir na lancheira escolar.",
    photo_url: null,
    youtube_videos: null,
    is_favorite: false,
    is_vivianne_safe: true,
    is_ticy_safe: false,
    times_used: 3,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "ticy",
    created_at: "2026-03-24T10:00:00Z",
  },

  {
    id: "recipe-32",
    household_id: "h1",
    name: "Wrap de Alface com Carne",
    category: "Lancheira",
    cuisine: null,
    tags: ["Rápida", "Sem Leite", "Sem Trigo", "Sem Ovos", "Low Carb"],
    prep_time_min: 15,
    servings: 2,
    difficulty: "Fácil",
    ingredients: [
      { name: "Folhas de alface iceberg", qty: 4, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Carne moída", qty: 250, unit: "g", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Tomate picado", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Abacate", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Limão", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
      { name: "Sal e pimenta", qty: 1, unit: "un", is_allergen_milk: false, is_allergen_wheat: false, is_allergen_egg: false },
    ],
    steps: [
      "Frigir a carne moída temperada com sal e pimenta.",
      "Lavar as folhas de alface grandes.",
      "Montar os wraps: carne, tomate e abacate na folha.",
      "Regar com limão e enrolar.",
    ],
    notes: "Low carb ideal para Vivianne. Sem trigo, sem leite.",
    photo_url: null,
    youtube_videos: null,
    is_favorite: false,
    is_vivianne_safe: true,
    is_ticy_safe: true,
    times_used: 4,
    last_used_at: null,
    parent_recipe_id: null,
    created_by: "vivianne",
    created_at: "2026-03-25T10:00:00Z",
  },
];
