/**
 * VENTIS — Scripts de Meditação e Afirmações
 * Chakra: Anahata (Coração) — 341Hz
 * Tema: Vento, Energia, Ritmo Natural, Equilíbrio
 *
 * Formato: array de strings — cada item = uma "unidade de respiração"
 * Compatível com ElevenLabs TTS + drone ventis-drone.mp3 como fundo
 */

export const MEDITACOES_VENTIS = [
  {
    id: 'ritmo_natural',
    slug: '25-ritmo-natural',
    nome: 'O Ritmo Natural do Teu Corpo',
    descricao: 'Meditação para reconectar com o teu próprio ritmo de energia, sem pressa nem culpa.',
    duracao_min: 10,
    categoria: 'meditacao',
    icone: '🍃',
    drone: 'ventis-drone.mp3',
    script: [
      'Encontra um lugar confortável. Senta-te ou deita-te.',
      'Fecha os olhos. Deixa os ombros descerem.',
      'Respira naturalmente. Sem forçar. Só observa.',
      'Cada pessoa tem um ritmo. O teu ritmo.',
      'Não é o ritmo do teu trabalho. Não é o ritmo da tua família.',
      'É o ritmo do teu corpo. Esse que existe antes do alarme tocar.',
      'Coloca uma mão sobre o coração. Sente-o bater.',
      'Este é o teu pulso mais honesto.',
      'Imagina agora que estás numa floresta. Vento suave nas folhas.',
      'As árvores não se apressam. Crescem no tempo delas.',
      'As folhas não se preocupam com amanhã. Estão aqui, no agora.',
      'Inspira o ar da floresta... fresco, limpo, cheio de vida.',
      'Expira tudo o que não é teu. O stress dos outros. As expectativas externas.',
      'O teu corpo sabe quando descansar. Sabe quando agir.',
      'O problema não é o teu corpo. É que raramente o ouvimos.',
      'Pergunta ao teu corpo agora: o que precisas hoje?',
      'Não a tua cabeça. O teu corpo. O que sentes?',
      'Cansaço? Movimento? Silêncio? Conexão?',
      'Seja qual for a resposta, é válida.',
      'O teu ritmo não precisa de justificação.',
      'Inspira... e compromete-te a honrar esse ritmo hoje.',
      'Quando abrires os olhos, leva esta pergunta contigo: o que o meu corpo precisa agora?',
    ],
  },
  {
    id: 'pausa_que_renova',
    slug: '26-pausa-que-renova',
    nome: 'Pausa Que Renova',
    descricao: 'Meditação para recuperar energia a meio do dia, em apenas seis minutos.',
    duracao_min: 6,
    categoria: 'meditacao',
    icone: '🌬️',
    drone: 'ventis-drone.mp3',
    script: [
      'Para. Mesmo aqui, mesmo agora.',
      'Não precisas de ir a lado nenhum. Só precisas de parar.',
      'Fecha os olhos por um momento.',
      'Inspira pelo nariz, conta até quatro.',
      'Segura o ar, conta até quatro.',
      'Expira pela boca, conta até seis.',
      'Repete isso mais duas vezes.',
      'Sente o teu corpo a abrandar. Como uma onda que chega à praia.',
      'Este momento de pausa não é preguiça. É inteligência.',
      'O teu sistema nervoso precisa de pausas para funcionar bem.',
      'Imagina que o teu corpo é um telefone. Pausar é carregar a bateria.',
      'Sem isso, entras em modo de sobrevivência. Reativo. Esgotado.',
      'Esta pausa é um presente que te dás.',
      'Inspira... energia nova.',
      'Expira... tensão acumulada.',
      'Quando continuares o teu dia, levas contigo esta calma.',
      'Podes voltar aqui sempre que precisares. É sempre teu.',
    ],
  },
  {
    id: 'raizes_no_vento',
    slug: '27-raizes-no-vento',
    nome: 'Raízes no Vento',
    descricao: 'Meditação para te manteres centrado mesmo nos dias de mais turbulência e exigência.',
    duracao_min: 8,
    categoria: 'meditacao',
    icone: '🌳',
    drone: 'ventis-drone.mp3',
    script: [
      'Fecha os olhos. Sente os pés no chão.',
      'Pressiona os pés suavemente contra o chão. Sente a firmeza.',
      'Imagina que és uma árvore.',
      'Alta. Forte. Com raízes profundas na terra.',
      'Acima de ti, o vento. Às vezes suave. Às vezes forte.',
      'Os teus galhos movem-se. Dobram-se com o vento.',
      'Mas as tuas raízes não se mexem.',
      'A vida vai trazer vento. Sempre trouxe. Sempre trará.',
      'Dias de exigência. Pessoas que drenam. Decisões difíceis.',
      'Podes dobrar. Não tens de quebrar.',
      'Inspira... e sente as raízes a aprofundar-se.',
      'Para o centro da terra. Estável. Seguro.',
      'Expira... e permite que os galhos se movam livremente.',
      'Flexível por cima. Inabalável por baixo.',
      'Esta é a tua natureza. Adaptável e enraizado ao mesmo tempo.',
      'Quando o vento vier hoje, lembra-te das tuas raízes.',
      'Elas estão sempre lá. Mesmo quando não as sentes.',
    ],
  },
  {
    id: 'energia_equilibrio',
    slug: '28-energia-equilibrio',
    nome: 'Energia em Equilíbrio',
    descricao: 'Afirmações para manter a tua energia estável e protegida ao longo do dia.',
    duracao_min: 3,
    categoria: 'afirmacoes',
    icone: '⚖️',
    drone: 'ventis-drone.mp3',
    script: [
      'Repete estas afirmações. Deixa cada uma assentar antes de passares à próxima.',
      'A minha energia é um recurso valioso e limitado.',
      'Eu escolho onde gasto a minha atenção.',
      'Dizer não é uma forma de dizer sim a mim.',
      'O descanso faz parte do meu desempenho.',
      'Não preciso de estar disponível para tudo o tempo todo.',
      'A minha energia renova-se quando a respeito.',
      'Eu reconheço os sinais do meu corpo antes de chegar ao limite.',
      'Pausar não é fraqueza. É estratégia.',
      'Eu alimento-me, durmo, movo-me. Cuido da minha máquina.',
      'A minha vitalidade é uma escolha diária.',
      'Hoje, honro o meu ritmo.',
    ],
  },
  {
    id: 'guardiao_ritmo',
    slug: '29-guardiao-ritmo',
    nome: 'Guardião do Meu Ritmo',
    descricao: 'Afirmações para dias de burnout ou quando sentes que perdeste o teu equilíbrio.',
    duracao_min: 3,
    categoria: 'afirmacoes',
    icone: '🛡️',
    drone: 'ventis-drone.mp3',
    script: [
      'Estás cansado. Isso é real. E não é fraqueza.',
      'Eu permito-me descansar sem culpa.',
      'O meu cansaço é informação. Não é fracasso.',
      'Eu não tenho de provar o meu valor através do esforço constante.',
      'A minha produtividade não define o meu valor como pessoa.',
      'Posso pedir ajuda. Posso dizer que estou esgotado.',
      'Recuperar é parte do processo. Não é interrupção.',
      'Amanhã serei mais forte por ter descansado hoje.',
      'Eu escolho o ritmo sustentável. Não o ritmo do mundo.',
      'O meu corpo merece atenção antes de entrar em colapso.',
      'Estou a aprender a ser guardião de mim.',
    ],
  },
]
